// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fd2544f-e42b-487e-93d2-a7aa2a0093e8"),
                            Description = "Canal dedicado a dotnet core",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("38a3c2c7-8381-45c9-90f8-5dde2a4036a2"),
                            Description = "Canal dedicado a AngularJS",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("16d21f9b-d7cb-44b3-b652-49cfa306d251"),
                            Description = "Canal dedicado a React JS",
                            Name = "React JS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
